name: Deploy prod

on:
  push:
    branches:
      - master

jobs:
  deploy:    
    permissions:
      contents: 'read'
      id-token: 'write'
    name: Deploy
    uses: ./.github/workflows/deploy-shared.yml
    with:
      gcpProjectId: kube-multi-container-app
      gkeZone: us-central1-c
    secrets:
      dockerUser: ${{ secrets.DOCKER_USER }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
      wifProvider: ${{ secrets.WIF_PROVIDER }}
      wifServiceAccount: ${{ secrets.WIF_SERVICE_ACCOUNT }}
